### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lines' of undefined

### ISSUE THREAD

**Issue by ACPK** [mochizukikotaro/print-code#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-beta0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [print-code](https://github.com/mochizukikotaro/print-code) package 0.6.2

### Stack Trace

Uncaught TypeError: Cannot read property 'lines' of undefined

```
At /Users/andrewkelley/.atom/packages/print-code/lib/print-code.js:70

TypeError: Cannot read property 'lines' of undefined
    at Object.print (/packages/print-code/lib/print-code.js:70:58)
    at /packages/print-code/lib/print-code.js:31:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:1300:1)
    at EventEmitter.outerCallback (/Applications/Atom Beta.app/Contents/Resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:36.1.0 core:paste (input.hidden-input)
     -8:31.6.0 core:confirm (input.hidden-input)
     -7:14.4.0 print-atom:print (input.hidden-input)
     -5:50.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -5:50.1.0 editor:consolidate-selections (input.hidden-input)
     -5:50.1.0 core:cancel (input.hidden-input)
     -5:46.9.0 print-atom:print (input.hidden-input)
     -3:19.5.0 core:backspace (input.hidden-input)
     -3:18.9.0 core:confirm (input.hidden-input)
  2x -1:42.5.0 print-code:print (input.hidden-input)
     -0:53.1.0 print-atom:print (input.hidden-input)
     -0:49.6.0 core:copy (input.hidden-input)
  2x -0:43 print-code:print (input.hidden-input)
     -0:22.2.0 editor:consolidate-selections (input.hidden-input)
     -0:22.2.0 core:cancel (input.hidden-input)
  2x -0:15.9.0 print-code:print (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-css-comb 3.1.0 
atomify 0.3.0 
busy-signal 1.4.1 
color-picker 2.2.5 
cucumber 0.6.0 
cucumber-step 0.2.0 
git-blame 1.1.1 
intentions 1.1.2 
language-docker 1.1.7 
language-haml 0.24.3 
language-rspec 0.6.2 
linter 2.1.4 
linter-haml 2.0.1 
linter-rubocop 2.1.1 
linter-ruby 1.2.5 
linter-scss-lint 3.1.0 
linter-ui-default 1.5.4 
markdown-themeable-pdf 1.2.0 
minimap 4.28.2 
print-atom 0.1.1 
print-code 0.6.2 
rails-i18n-autocomplete 0.4.0 
rails-latest-migration 1.1.6 
rails-open-rspec 1.2.0 
ruby-block-converter 3.5.0 
ruby-slim 0.2.0 
ruby-test 1.0.2 
Sublime-Style-Column-Selection 1.7.4 
toggle-quotes 1.0.1 
trailing-spaces 0.4.0 
translator 0.3.0 
```

**Comment by mochizukikotaro** [comment]
@ACPK Thank you for you error report.

When `ActivePaneItem` is not `TextEditor`(ex. TreeView ), this error is occurs. 
So please select a TextEditor which you want to print and try to `print-code`. 🙇 

I will try to fix this error.

----
<img width="1277" alt="2017-05-22 10 44 09" src="https://cloud.githubusercontent.com/assets/7911481/26289528/c8d20d22-3edb-11e7-8471-f8ee90772311.png">

You can check an `ActivePaneItem` on the console.

```
atom.workspace.getActivePaneItem()
```

**Comment by mochizukikotaro** [comment]
@ACPK I merged https://github.com/mochizukikotaro/print-code/pull/7/files .

- Remove unnecessary code
- Add todo comment

Thanks!
