### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setSoftWrapped' of undefined

### ISSUE THREAD

**Issue by respawnface** [mochizukikotaro/print-code#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [print-code](https://github.com/mochizukikotaro/print-code) package 0.6.4

### Stack Trace

Uncaught TypeError: Cannot read property 'setSoftWrapped' of undefined

```
At C:\Users\respawn\.atom\packages\print-code\lib\print-code.js:76

TypeError: Cannot read property 'setSoftWrapped' of undefined
    at Object.print (/packages/print-code/lib/print-code.js:76:41)
    at /packages/print-code/lib/print-code.js:31:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.17.0/resources/app/src/atom-environment.js:1286:1)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.17.0/resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:57.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -3:57.3.0 print-code:print (input.hidden-input)
     -3:37.4.0 print-atom:print (input.hidden-input)
  2x -2:53.5.0 print-code:print (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.6 
minimap 4.28.2 
pigments 0.39.1 
print-atom 0.1.1 
print-code 0.6.4 
```

**Comment by Milchreis** [comment]
Info: I had the same error by trying to print a markdown preview.

**Comment by PapsOu** [comment]
Same error with a RST preview too
