### ISSUE TITLE
Uncaught ReferenceError: elements is not defined

### ISSUE THREAD

**Issue by esponapule** [mochizukikotaro/print-code#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.1 x64
**Electron**: 1.3.15
**OS**: Debian GNU/Linux
**Thrown From**: [print-code](https://github.com/mochizukikotaro/print-code) package 0.6.4

### Stack Trace

Uncaught ReferenceError: elements is not defined

```
At /home/esponapule/.atom/packages/print-code/lib/print-code.js:61

ReferenceError: elements is not defined
    at Object.reset (/packages/print-code/lib/print-code.js:61:7)
    at /packages/print-code/lib/print-code.js:32:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1300:1)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:52.3.0 intentions:highlight (input.hidden-input)
     -3:52.1.0 core:paste (input.hidden-input)
     -3:48.9.0 core:backspace (input.hidden-input)
     -3:13.8.0 core:delete (input.hidden-input)
     -3:02.9.0 intentions:highlight (input.hidden-input)
     -3:02.7.0 core:undo (input.hidden-input)
  2x -2:35.1.0 core:delete (input.hidden-input)
 16x -2:21 core:backspace (input.hidden-input)
     -1:49.5.0 text-manipulation:whitespace-emptylines (input.hidden-input)
     -1:47 intentions:highlight (input.hidden-input)
     -1:46.9.0 core:select-all (input.hidden-input)
     -1:38.7.0 text-manipulation:whitespace-emptylines (input.hidden-input)
     -1:11 whitespace:remove-trailing-whitespace (input.hidden-input)
     -0:43.2.0 settings-view:open (input.hidden-input)
     -0:28.8.0 core:confirm (input.hidden-input)
     -0:09.8.0 print-code:reset (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-css-comb 3.1.0 
atom-htmltidy 5.1.0 
atom-latex 0.7.9 
atom-live-server 2.1.2 
atom-prettify 0.1.3 
atom-python-run 0.7.3 
atom-runner 2.7.1 
atom-toolbar 0.1.6 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-python 1.8.63 
bracket-close-jump 0.1.2 
busy-signal 1.4.1 
case-switch 2.2.4 
change-case 0.6.5 
close-tags 0.6.0 
color-picker 2.2.5 
drag-drop-text 0.1.4 
file-icons 2.1.6 
flex-tool-bar 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-latex 1.0.0 
language-markdown 0.22.0 
latex 0.43.0 
lines 0.13.1 
linkify 0.11.0 
linter 2.1.4 
linter-languagetool 0.4.1 
linter-php 1.3.2 
linter-python 3.1.2 
linter-spell-html 0.6.2 
linter-ui-default 1.6.0 
markdown-assistant 0.2.0 
markdown-helpers 0.3.0 
markdown-pdf 1.5.0 
markdown-preview-enhanced 0.12.3 
markdown-preview-plus 2.4.9 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
markdown-toolbar 0.1.2 
markdown-writer 2.6.5 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
open-in-browser 0.5.0 
open-recent 5.0.0 
pandoc-convert 1.1.0 
php-cs-fixer 4.1.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
pretty-json 1.6.3 
print-code 0.6.4 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
simple-drag-drop-text 0.3.4 
smart-quotes-plus 2.1.0 
smarter-delete-line 1.1.2 
sort-lines 0.14.0 
spell-check-project 0.7.0 
Sublime-Style-Column-Selection 1.7.4 
tag 0.5.0 
text-manipulation 0.6.0 
tidy-markdown 3.0.1 
title-case 0.4.0 
tool-bar 1.1.0 
tool-bar-config 0.1.0 
tool-bar-main 0.0.10 
tool-bar-markdown-writer 0.2.0 
toolbar-iconshortcuts 3.13.0 
trailing-spaces 0.4.0 
url-utils 0.2.1 
wordcount 2.10.4 
```

**Comment by ryanmgregory** [comment]
<img width="470" alt="Screen Shot 2020-02-20 at 2 50 22 PM" src="https://user-images.githubusercontent.com/57638436/74977460-5dd94d00-53f0-11ea-8571-3eed87d3ac2a.png">

[steps to reproduce]

1. CMND + SHIFT + p
2. type 'print code'
3. hit 'enter'
